foreach(DIR ${SOURCES_REC_DIRS})
  file(GLOB_RECURSE TMP_SOURCES RELATIVE ${MODULE_PATH} ${DIR}/*.cpp)
  #message(${TMP_SOURCES})
  set(SOURCES ${SOURCES} ${TMP_SOURCES})
endforeach()

foreach(DIR ${SOURCES_DIRS})
  file(GLOB TMP_SOURCES RELATIVE ${MODULE_PATH} ${DIR}/*.cpp)
  #message(${TMP_SOURCES})
  set(SOURCES ${SOURCES} ${TMP_SOURCES})
endforeach()

include_directories(${MODULE_PATH})
if (OBJECT_LIB)
add_library(${MODULE_NAME} OBJECT ${SOURCES})
else()
add_library(${MODULE_NAME} STATIC ${SOURCES})
endif()
set(SOURCES )
set(SOURCES_DIRS )
set(SOURCES_REC_DIRS )