#include "system_example.inl"
ecs\system_example.inl test_system
Type[int] Name[a]
Type[float] Name[b]
Type[std::string] Name[s_s]
Type[C] Name[cp_v_ls][optional]
Type[D] Name[d]
ecs\system_example.inl Lol_system
Type[A] Name[a1]
Type[B] Name[b2]
Type[std::string] Name[s3]
Type[C] Name[c][optional]
Type[D] Name[d]
